
/* 
	Copyright (c) 2018 Azeez Adewale <azeezadewale98@gmail.com> 
	MIT License Copyright (c) 2018 simple-lang 

*/
/*
	this is an example of using the try..catch to debug 
	error at runtime and prevent program from exiting after an error
*/
/*
	a try...catch block that have a custom error message
*/
one = 30
try 
	one = 70
	display 453 + ["ade", "wale"] 
	one = 90
catch 
	display "error occur" + nl
end
display one

/*
	a try...catch block which display the actual error that occur
*/
try {
	display 453 + ["ade", "wale"] 
catch
	display nl + __err__
}
